-- Rodar no Supabase SQL Editor
-- https://supabase.com/dashboard/project/vatkfkdnflbdfomglvme/sql/new

-- ── Compromissos ──────────────────────────────────────────────
create table if not exists appointments (
  id            bigint generated by default as identity primary key,
  title         text not null,
  description   text,
  scheduled_at  bigint not null,  -- Unix ms timestamp
  is_done       boolean not null default false,
  alert_minutes_before integer,
  client_id     bigint references clients(id) on delete set null,
  created_at    timestamptz not null default now()
);

alter table appointments enable row level security;
create policy "allow all" on appointments for all using (true) with check (true);

-- ── Alarmes Pessoais ──────────────────────────────────────────
create table if not exists reminders (
  id               bigint generated by default as identity primary key,
  title            text not null,
  description      text,
  type             text not null default 'interval', -- 'interval' | 'daily'
  interval_minutes integer,
  daily_time       text,  -- 'HH:MM'
  is_active        boolean not null default true,
  created_at       timestamptz not null default now()
);

alter table reminders enable row level security;
create policy "allow all" on reminders for all using (true) with check (true);

-- ── Coluna extra em scheduled_tasks (se não existir) ──────────
alter table scheduled_tasks
  add column if not exists alert_minutes_before integer,
  add column if not exists client_id bigint references clients(id) on delete set null;
